# Generated by Django 3.2.9 on 2021-11-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_blog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
