# Generated by Django 3.2.9 on 2021-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extra_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
