# Generated by Django 3.2.9 on 2021-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20211109_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(choices=[('TECH', 'TECH'), ('JOBS', 'JOBS'), ('DJANGO', 'DJANGO'), ('REACT', 'REACT')], default='TECH', max_length=100),
        ),
    ]
